/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.event.EventHandler;
import javafx.geometry.HPos;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.*;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Application.launch(args);
    }

    public void start(Stage stage)throws Exception{
        Scene sc = new Scene(buildGrid(stage));
        stage.setScene(sc);
        stage.show();
    }

    private GridPane buildGrid(Stage stage){
        stage.setTitle("Acquire");
        //Labels for Letters
        Label aLabel = new Label ("A");
        Label bLabel = new Label ("B");
        Label cLabel = new Label ("C");
        Label dLabel = new Label ("D");
        Label eLabel = new Label ("E");
        Label fLabel = new Label ("F");
        Label gLabel = new Label ("G");
        Label hLabel = new Label ("H");
        Label iLabel = new Label ("I");
        //Labels for Numbers
        Label oneLabel = new Label ("1");
        Label twoLabel = new Label ("2");
        Label threeLabel = new Label ("3");
        Label fourLabel = new Label ("4");
        Label fiveLabel = new Label ("5");
        Label sixLabel = new Label ("6");
        Label sevenLabel = new Label ("7");
        Label eightLabel = new Label ("8");
        Label nineLabel = new Label ("9");
        Label tenLabel = new Label ("10");
        Label elevenLabel = new Label ("11");
        Label twelveLabel = new Label ("12");
        //Labels for Literally Everything
        Label aOneLabel = new Label("A1");
        Label aTwoLabel = new Label("A2");
        Label aThreeLabel = new Label("A3");
        Label aFourLabel = new Label("A4");
        Label aFiveLabel = new Label("A5");
        Label aSixLabel = new Label("A6");
        Label aSevenLabel = new Label("A7");
        Label aEightLabel = new Label("A8");
        Label aNineLabel = new Label("A9");
        Label aTenLabel = new Label("A10");
        Label aElevenLabel = new Label("A11");
        Label aTwelveLabel = new Label("A12");

        Label bOneLabel = new Label("B1");
        Label bTwoLabel = new Label("B2");
        Label bThreeLabel = new Label("B3");
        Label bFourLabel = new Label("B4");
        Label bFiveLabel = new Label("B5");
        Label bSixLabel = new Label("B6");
        Label bSevenLabel = new Label("B7");
        Label bEightLabel = new Label("B8");
        Label bNineLabel = new Label("B9");
        Label bTenLabel = new Label("B10");
        Label bElevenLabel = new Label("B11");
        Label bTwelveLabel = new Label("B12");

        Label cOneLabel = new Label("C1");
        Label cTwoLabel = new Label("C2");
        Label cThreeLabel = new Label("C3");
        Label cFourLabel = new Label("C4");
        Label cFiveLabel = new Label("C5");
        Label cSixLabel = new Label("C6");
        Label cSevenLabel = new Label("C7");
        Label cEightLabel = new Label("C8");
        Label cNineLabel = new Label("C9");
        Label cTenLabel = new Label("C10");
        Label cElevenLabel = new Label("C11");
        Label cTwelveLabel = new Label("C12");

        Label dOneLabel = new Label("D1");
        Label dTwoLabel = new Label("D2");
        Label dThreeLabel = new Label("D3");
        Label dFourLabel = new Label("D4");
        Label dFiveLabel = new Label("D5");
        Label dSixLabel = new Label("D6");
        Label dSevenLabel = new Label("D7");
        Label dEightLabel = new Label("D8");
        Label dNineLabel = new Label("D9");
        Label dTenLabel = new Label("D10");
        Label dElevenLabel = new Label("D11");
        Label dTwelveLabel = new Label("D12");

        Label eOneLabel = new Label("E1");
        Label eTwoLabel = new Label("E2");
        Label eThreeLabel = new Label("E3");
        Label eFourLabel = new Label("E4");
        Label eFiveLabel = new Label("E5");
        Label eSixLabel = new Label("E6");
        Label eSevenLabel = new Label("E7");
        Label eEightLabel = new Label("E8");
        Label eNineLabel = new Label("E9");
        Label eTenLabel = new Label("E10");
        Label eElevenLabel = new Label("E11");
        Label eTwelveLabel = new Label("E12");

        Label fOneLabel = new Label("F1");
        Label fTwoLabel = new Label("F2");
        Label fThreeLabel = new Label("F3");
        Label fFourLabel = new Label("F4");
        Label fFiveLabel = new Label("F5");
        Label fSixLabel = new Label("F6");
        Label fSevenLabel = new Label("F7");
        Label fEightLabel = new Label("F8");
        Label fNineLabel = new Label("F9");
        Label fTenLabel = new Label("F10");
        Label fElevenLabel = new Label("F11");
        Label fTwelveLabel = new Label("F12");

        Label gOneLabel = new Label("G1");
        Label gTwoLabel = new Label("G2");
        Label gThreeLabel = new Label("G3");
        Label gFourLabel = new Label("G4");
        Label gFiveLabel = new Label("G5");
        Label gSixLabel = new Label("G6");
        Label gSevenLabel = new Label("G7");
        Label gEightLabel = new Label("G8");
        Label gNineLabel = new Label("G9");
        Label gTenLabel = new Label("G10");
        Label gElevenLabel = new Label("G11");
        Label gTwelveLabel = new Label("G12");

        Label hOneLabel = new Label("H1");
        Label hTwoLabel = new Label("H2");
        Label hThreeLabel = new Label("H3");
        Label hFourLabel = new Label("H4");
        Label hFiveLabel = new Label("H5");
        Label hSixLabel = new Label("H6");
        Label hSevenLabel = new Label("H7");
        Label hEightLabel = new Label("H8");
        Label hNineLabel = new Label("H9");
        Label hTenLabel = new Label("H10");
        Label hElevenLabel = new Label("H11");
        Label hTwelveLabel = new Label("H12");

        Label iOneLabel = new Label("I1");
        Label iTwoLabel = new Label("I2");
        Label iThreeLabel = new Label("I3");
        Label iFourLabel = new Label("I4");
        Label iFiveLabel = new Label("I5");
        Label iSixLabel = new Label("I6");
        Label iSevenLabel = new Label("I7");
        Label iEightLabel = new Label("I8");
        Label iNineLabel = new Label("I9");
        Label iTenLabel = new Label("I10");
        Label iElevenLabel = new Label("I11");
        Label iTwelveLabel = new Label("I12");
        //Buttons
        Button loadButton = new Button("Load Game");
        Button saveButton = new Button("Save Game");
        Button hotelButton = new Button("Hotels");
        Button stocksButton = new Button("Stocks");
        Button infoButton = new Button("Info");
        //Player Info
        Label pLabel = new Label("PLAYER INFO:");

        Label tLabel = new Label("TILES: 1.-- 2.-- 3.-- 4.-- 5.-- 6.--");

        Label mLabel = new Label("MONEY: $----");
        //grid setup
        GridPane gp = new  GridPane();
        gp.add(oneLabel,1,0);
        gp.add(twoLabel,2,0);
        gp.add(threeLabel,3,0);
        gp.add(fourLabel,4,0);
        gp.add(fiveLabel,5,0);
        gp.add(sixLabel,6,0);
        gp.add(sevenLabel,7,0);
        gp.add(eightLabel,8,0);
        gp.add(nineLabel,9,0);
        gp.add(tenLabel,10,0);
        gp.add(elevenLabel,11,0);
        gp.add(twelveLabel,12,0);

        gp.add(aLabel,0,1);
        gp.add(aOneLabel,1,1);
        gp.add(aTwoLabel,2,1);
        gp.add(aThreeLabel,3,1);
        gp.add(aFourLabel,4,1);
        gp.add(aFiveLabel,5,1);
        gp.add(aSixLabel,6,1);
        gp.add(aSevenLabel,7,1);
        gp.add(aEightLabel,8,1);
        gp.add(aNineLabel,9,1);
        gp.add(aTenLabel,10,1);
        gp.add(aElevenLabel,11,1);
        gp.add(aTwelveLabel,12,1);

        gp.add(bLabel,0,2);
        gp.add(bOneLabel,1,2);
        gp.add(bTwoLabel,2,2);
        gp.add(bThreeLabel,3,2);
        gp.add(bFourLabel,4,2);
        gp.add(bFiveLabel,5,2);
        gp.add(bSixLabel,6,2);
        gp.add(bSevenLabel,7,2);
        gp.add(bEightLabel,8,2);
        gp.add(bNineLabel,9,2);
        gp.add(bTenLabel,10,2);
        gp.add(bElevenLabel,11,2);
        gp.add(bTwelveLabel,12,2);


        gp.add(cLabel,0,3);
        gp.add(cOneLabel,1,3);
        gp.add(cTwoLabel,2,3);
        gp.add(cThreeLabel,3,3);
        gp.add(cFourLabel,4,3);
        gp.add(cFiveLabel,5,3);
        gp.add(cSixLabel,6,3);
        gp.add(cSevenLabel,7,3);
        gp.add(cEightLabel,8,3);
        gp.add(cNineLabel,9,3);
        gp.add(cTenLabel,10,3);
        gp.add(cElevenLabel,11,3);
        gp.add(cTwelveLabel,12,3);

        gp.add(dLabel,0,4);
        gp.add(dOneLabel,1,4);
        gp.add(dTwoLabel,2,4);
        gp.add(dThreeLabel,3,4);
        gp.add(dFourLabel,4,4);
        gp.add(dFiveLabel,5,4);
        gp.add(dSixLabel,6,4);
        gp.add(dSevenLabel,7,4);
        gp.add(dEightLabel,8,4);
        gp.add(dNineLabel,9,4);
        gp.add(dTenLabel,10,4);
        gp.add(dElevenLabel,11,4);
        gp.add(dTwelveLabel,12,4);

        gp.add(eLabel,0,5);
        gp.add(eOneLabel,1,5);
        gp.add(eTwoLabel,2,5);
        gp.add(eThreeLabel,3,5);
        gp.add(eFourLabel,4,5);
        gp.add(eFiveLabel,5,5);
        gp.add(eSixLabel,6,5);
        gp.add(eSevenLabel,7,5);
        gp.add(eEightLabel,8,5);
        gp.add(eNineLabel,9,5);
        gp.add(eTenLabel,10,5);
        gp.add(eElevenLabel,11,5);
        gp.add(eTwelveLabel,12,5);

        gp.add(fLabel,0,6);
        gp.add(fOneLabel,1,6);
        gp.add(fTwoLabel,2,6);
        gp.add(fThreeLabel,3,6);
        gp.add(fFourLabel,4,6);
        gp.add(fFiveLabel,5,6);
        gp.add(fSixLabel,6,6);
        gp.add(fSevenLabel,7,6);
        gp.add(fEightLabel,8,6);
        gp.add(fNineLabel,9,6);
        gp.add(fTenLabel,10,6);
        gp.add(fElevenLabel,11,6);
        gp.add(fTwelveLabel,12,6);

        gp.add(gLabel,0,7);
        gp.add(gOneLabel,1,7);
        gp.add(gTwoLabel,2,7);
        gp.add(gThreeLabel,3,7);
        gp.add(gFourLabel,4,7);
        gp.add(gFiveLabel,5,7);
        gp.add(gSixLabel,6,7);
        gp.add(gSevenLabel,7,7);
        gp.add(gEightLabel,8,7);
        gp.add(gNineLabel,9,7);
        gp.add(gTenLabel,10,7);
        gp.add(gElevenLabel,11,7);
        gp.add(gTwelveLabel,12,7);

        gp.add(hLabel,0,8);
        gp.add(hOneLabel,1,8);
        gp.add(hTwoLabel,2,8);
        gp.add(hThreeLabel,3,8);
        gp.add(hFourLabel,4,8);
        gp.add(hFiveLabel,5,8);
        gp.add(hSixLabel,6,8);
        gp.add(hSevenLabel,7,8);
        gp.add(hEightLabel,8,8);
        gp.add(hNineLabel,9,8);
        gp.add(hTenLabel,10,8);
        gp.add(hElevenLabel,11,8);
        gp.add(hTwelveLabel,12,8);

        gp.add(iLabel,0,9);
        gp.add(iOneLabel,1,9);
        gp.add(iTwoLabel,2,9);
        gp.add(iThreeLabel,3,9);
        gp.add(iFourLabel,4,9);
        gp.add(iFiveLabel,5,9);
        gp.add(iSixLabel,6,9);
        gp.add(iSevenLabel,7,9);
        gp.add(iEightLabel,8,9);
        gp.add(iNineLabel,9,9);
        gp.add(iTenLabel,10,9);
        gp.add(iElevenLabel,11,9);
        gp.add(iTwelveLabel,12,9);

        gp.add(loadButton,0,16);
        gp.add(saveButton,1,16);
        gp.add(tLabel,2,16);
        gp.add(mLabel,3,16);
        gp.add(hotelButton,4,16);
        gp.add(stocksButton,5,16);
        gp.add(infoButton,6,16);
        gp.add(pLabel,2,15);

        return gp;





    }







}

    /*//Start App
        Game g = new Game();
        int PlayerID = g.determineFirst();

        //Play a Tile
        Player p = new Player(99,"Free");
        g.playTile(new Tile(1,1));
        List<Tile> testFound = g.playTile(new Tile(2,1));
        g.foundHotel(0, 0, testFound);
        g.playTile(new Tile(1,2));

        //Buy Stock
        g.buyStock(1,0,3);

        //Save Game
        //g.saveGame("test.txt");

        //Load Game
        g.loadGame("test.txt");

        Player pp = new Player(99,"Free");*/
