/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        //Start App
        Game g = new Game();
        int PlayerID = g.determineFirst();

        //Play a Tile
        Player p = new Player(99,"Free");
        g.playTile(new Tile(1,1));
        List<Tile> testFound = g.playTile(new Tile(2,1));
        g.foundHotel(0, 0, testFound);
        g.playTile(new Tile(1,2));

        //Buy Stock
        g.buyStock(0,0,3);

    }
}
